### ISSUE TITLE
(Question) How to send message from an outside ikisocket code?

### ISSUE THREAD

**Issue by alvesoaj** [antoniodipinto/ikisocket#16]
Thanks for this package.

I have one application that uses Gorm to deal with database models, and in there there are callbacks like BeforeCreate or AfterSave...

My question is, how to emit ou send messages from inside these callbacks, or even from regular Fiber endpoints?

Do ikisocket public/global functions do this kind of job?

**Comment by antoniodipinto** [comment]
Hi,

If I understand correctly your question, yes, public functions will help you achieve this. Just remember the fact that you still need to have the ID of the socket to send messages to a specific client.

Thank you for you support :)

**Comment by alvesoaj** [comment]
Thanks, @antoniodipinto, I will use Redis to store the IDs. When I finish it I will back here and tell the story.
