### ISSUE TITLE
Upgrade to Fiber V2

### ISSUE THREAD

**Issue by sebastianbuechler** [antoniodipinto/ikisocket#3]
Is there an upgrade to Fiber V2 planned?

**Comment by antoniodipinto** [comment]
Hi @sebastianbuechler thanks for your contribution!
I'm testing everything on Travis right now. If everything goes well, starting from tonight ikisocket can support Fiber v2

**Comment by sebastianbuechler** [comment]
@antoniodipinto That would be awesome!

**Comment by antoniodipinto** [comment]
#4 Merged and built with Travis
