### ISSUE TITLE
Allow Access to ws variable

### ISSUE THREAD

**Issue by VaishakVk** [antoniodipinto/ikisocket#30]
**Is your feature request related to a problem? Please describe.**
I am trying to set Read Deadline everytime I receive a ping/pong to keep the connection alive. By default, it is 15 minutes which seems long. I wanted to set the read deadline using `ws.SetReadDeadline` but looks like `ws` is not available to accessed from outside. 

**Describe the solution you'd like**
Allow `ws` to be accessed from outside as `Ws`

**Describe alternatives you've considered**

**Additional context**

**Comment by antoniodipinto** [comment]
Will be implemented soon

**Comment by antoniodipinto** [comment]
@VaishakVk can be accessed via **Conn** variable
