### ISSUE TITLE
Connection with gofiber

### ISSUE THREAD

**Issue by ReneWerner87** [antoniodipinto/ikisocket#38]
hi, i´m rene (maintainer of the gofiber project)

to enable gofiber users to find your work, we should add the repository to [awesome-fiber](https://github.com/gofiber/awesome-fiber)
can you(@antoniodipinto ) do that?

what do you think about including your work in our [contrib](https://github.com/gofiber/contrib) repository, either as a separate package or under the [websocket](https://github.com/gofiber/contrib/tree/main/websocket) package ?

**Comment by ReneWerner87** [comment]
i also think we should provide more examples -> maybe in the [recipes](https://github.com/gofiber/recipes/blob/master/README.md) repository

**Comment by antoniodipinto** [comment]
Sure, that's a great idea. Thanks @ReneWerner87
