### ISSUE TITLE
[Request] Chat Room Example or Wrapper Feature for chat room

### ISSUE THREAD

**Issue by ryanakbarf** [antoniodipinto/ikisocket#8]
Hi, last week I contact you through twitter..

Could you please give us example on how to make chat rooms so we can implement multiple chat room in our websocket. Thanks a lot!

**Comment by antoniodipinto** [comment]
Hi, I will check if I will integrate it directly into the wrapper or I will edit the README file to contains also the groups inside

**Comment by ryanakbarf** [comment]
thanks... will wait..

**Comment by antoniodipinto** [comment]
Hi, after some digging I think that the best way to accomplish this is adding the group chat example in the readme, not changing the wrapper itself.
The library/wrapper work is just to simplify more complex functions down the code. The idea of groups/chat rooms is related more the business logic. So I will add some examples in the code but not changing the wrapper

**Comment by antoniodipinto** [comment]
Hi @ryanakbarf  a chat room example it's [here](https://github.com/antoniodipinto/ikisocket/tree/master/examples). Please feel free to add comments or improvements
